
import type { NewsArticle, Category, Permission } from './types';

export interface LanguageOption {
  value: string;
  label: string;
}

export const languageOptions: LanguageOption[] = [
  { value: 'bn', label: 'Bengali (বাংলা)' },
  { value: 'en', label: 'English' },
  { value: 'hi', label: 'Hindi (हिन्दी)' },
  { value: 'es', label: 'Spanish (Español)' },
  { value: 'fr', label: 'French (Français)' },
  { value: 'ar', label: 'Arabic (العربية)' },
  { value: 'de', label: 'German (Deutsch)' },
  { value: 'ja', label: 'Japanese (日本語)' },
  { value: 'pt', label: 'Portuguese (Português)' },
  { value: 'ru', label: 'Russian (Русский)' },
];

export const defaultLanguage: string = 'bn'; 

export const uiTexts: Record<string, Record<string, string>> = {
  en: {
    appName: "Samay Barta Lite",
    searchPlaceholder: "Search news...",
    allCategories: "All",
    technologyCategory: "Technology",
    sportsCategory: "Sports",
    businessCategory: "Business",
    worldCategory: "World",
    entertainmentCategory: "Entertainment",
    seeMore: "See More",
    backToNews: "Back to News",
    articleNotFound: "Article not found.",
    translationSuccessful: "Translation Successful",
    articleTranslatedTo: "Article translated to",
    translationFailed: "Translation Failed",
    couldNotTranslateArticle: "Could not translate the article. Please try again.",
    displayingOriginal: "Displaying Original",
    showingOriginalContent: "Showing the original article content.",
    translating: "Translating...",
    translateContent: "Translate Content",
    showOriginal: "Show Original",
    footerReserved: "All rights reserved.",
    footerPoweredBy: "Powered by Samay Barta Lite",
    theme: "Theme",
    lightTheme: "Light",
    darkTheme: "Dark",
    language: "Language",
    faq: "FAQ",
    termsAndConditions: "Terms & Conditions",
    faqTitle: "Frequently Asked Questions",
    termsTitle: "Terms and Conditions",
    loading: "Loading...",
    noArticlesFound: "No news articles found matching your criteria.",
    articleTitleLabel: "Title",
    articleContentLabel: "Content",
    publishedDateLabel: "Published",
    error: "Error",
    seoSiteTitleLabel: "Site Title",
    seoMetaDescriptionLabel: "Meta Description",
    seoMetaKeywordsLabel: "Meta Keywords (comma-separated)",
    seoFaviconUrlLabel: "Favicon URL",
    seoOgSiteNameLabel: "Open Graph Site Name",
    seoOgLocaleLabel: "Open Graph Locale (e.g., en_US)",
    seoOgTypeLabel: "Open Graph Type (e.g., website)",
    seoTwitterCardLabel: "Twitter Card Type",
    seoTwitterSiteLabel: "Twitter Site Handle (e.g., @username)",
    seoTwitterCreatorLabel: "Twitter Creator Handle (Optional)",
    seoSettingsSaved: "SEO settings saved successfully.",
    seoSettingsError: "Error saving SEO settings.",
    articleMetaTitleLabel: "Meta Title (SEO)",
    articleMetaDescriptionLabel: "Meta Description (SEO)",
    articleMetaKeywordsLabel: "Meta Keywords (SEO, comma-separated)",
    articleOgTitleLabel: "Open Graph Title (Social)",
    articleOgDescriptionLabel: "Open Graph Description (Social)",
    articleOgImageLabel: "Open Graph Image URL (Social)",
    articleCanonicalUrlLabel: "Canonical URL (Advanced)",
    // User Roles related texts
    manageUsers: "Manage Users & Roles",
    username: "Username",
    email: "Email",
    password: "Password",
    roles: "Roles",
    userActive: "User Active",
    addUser: "Add User",
    editUser: "Edit User",
    deleteUser: "Delete User",
    confirmDeleteUser: "Are you sure you want to delete this user?",
    userCreated: "User created successfully.",
    userUpdated: "User updated successfully.",
    userDeleted: "User deleted successfully.",
    manageRoles: "Manage Roles",
    roleName: "Role Name",
    roleDescription: "Description (Optional)",
    permissions: "Permissions",
    addRole: "Add Role",
    editRole: "Edit Role",
    deleteRole: "Delete Role",
    confirmDeleteRole: "Are you sure you want to delete this role? This will unassign it from all users.",
    roleCreated: "Role created successfully.",
    roleUpdated: "Role updated successfully.",
    roleDeleted: "Role deleted successfully.",
    cancel: "Cancel",
    save: "Save",
    viewAdminDashboardPermission: "View Admin Dashboard",
    manageArticlesPermission: "Manage Articles",
    publishArticlesPermission: "Publish Articles",
    manageUsersPermission: "Manage Users",
    manageRolesPermission: "Manage Roles",
    manageLayoutGadgetsPermission: "Manage Layout/Gadgets",
    manageSeoGlobalPermission: "Manage Global SEO",
    manageSettingsPermission: "Manage Site Settings",
    userAndRoleManagement: "User & Role Mgmt",
    activityLog: "Activity Log",
  },
  bn: {
    appName: "সময় বার্তা লাইট",
    searchPlaceholder: "খবর অনুসন্ধান করুন...",
    allCategories: "সব",
    technologyCategory: "প্রযুক্তি",
    sportsCategory: "খেলাধুলা",
    businessCategory: "ব্যবসা",
    worldCategory: "বিশ্ব",
    entertainmentCategory: "বিনোদন",
    seeMore: "আরও দেখুন",
    backToNews: " খবরে ফিরুন",
    articleNotFound: "নিবন্ধটি খুঁজে পাওয়া যায়নি।",
    translationSuccessful: "অনুবাদ সফল হয়েছে",
    articleTranslatedTo: "নিবন্ধটি অনুবাদ করা হয়েছে",
    translationFailed: "অনুবাদ ব্যর্থ হয়েছে",
    couldNotTranslateArticle: "নিবন্ধটি অনুবাদ করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।",
    displayingOriginal: "মূল বিষয়বস্তু প্রদর্শিত হচ্ছে",
    showingOriginalContent: "নিবন্ধটির মূল বিষয়বস্তু দেখানো হচ্ছে।",
    translating: "অনুবাদ করা হচ্ছে...",
    translateContent: "বিষয়বস্তু অনুবাদ করুন",
    showOriginal: "মূল দেখান",
    footerReserved: "সর্বস্বত্ব সংরক্ষিত।",
    footerPoweredBy: "সময় বার্তা লাইট দ্বারা চালিত",
    theme: "থিম",
    lightTheme: "লাইট",
    darkTheme: "ডার্ক",
    language: "ভাষা",
    faq: "প্রশ্নাবলী",
    termsAndConditions: "শর্তাবলী",
    faqTitle: "সাধারণ জিজ্ঞাস্য প্রশ্নাবলী",
    termsTitle: "শর্তাবলী এবং নিয়মাবলী",
    loading: "লোড হচ্ছে...",
    noArticlesFound: "আপনার মানদণ্ডের সাথে মিলে যাওয়া কোনও সংবাদ নিবন্ধ পাওয়া যায়নি।",
    articleTitleLabel: "শিরোনাম",
    articleContentLabel: "বিষয়বস্তু",
    publishedDateLabel: "প্রকাশিত",
    error: "ত্রুটি",
    seoSiteTitleLabel: "সাইটের শিরোনাম",
    seoMetaDescriptionLabel: "মেটা বর্ণনা",
    seoMetaKeywordsLabel: "মেটা কীওয়ার্ড (কমা দ্বারা পৃথক)",
    seoFaviconUrlLabel: "ফ্যাভিকন ইউআরএল",
    seoOgSiteNameLabel: "ওপেন গ্রাফ সাইটের নাম",
    seoOgLocaleLabel: "ওপেন গ্রাফ লোকেল (যেমন, bn_BD)",
    seoOgTypeLabel: "ওপেন গ্রাফ প্রকার (যেমন, website)",
    seoTwitterCardLabel: "টুইটার কার্ড প্রকার",
    seoTwitterSiteLabel: "টুইটার সাইট হ্যান্ডেল (যেমন, @username)",
    seoTwitterCreatorLabel: "টুইটার ক্রিয়েটর হ্যান্ডেল (ঐচ্ছিক)",
    seoSettingsSaved: "এসইও সেটিংস সফলভাবে সংরক্ষণ করা হয়েছে।",
    seoSettingsError: "এসইও সেটিংস সংরক্ষণ করতে ত্রুটি।",
    articleMetaTitleLabel: "মেটা শিরোনাম (এসইও)",
    articleMetaDescriptionLabel: "মেটা বর্ণনা (এসইও)",
    articleMetaKeywordsLabel: "মেটা কীওয়ার্ড (এসইও, কমা দ্বারা পৃথক)",
    articleOgTitleLabel: "ওপেন গ্রাফ শিরোনাম (সোশ্যাল)",
    articleOgDescriptionLabel: "ওপেন গ্রাফ বর্ণনা (সোশ্যাল)",
    articleOgImageLabel: "ওপেন গ্রাফ ছবির ইউআরএল (সোশ্যাল)",
    articleCanonicalUrlLabel: "ক্যানোনিকাল ইউআরএল (অ্যাডভান্সড)",
    // User Roles related texts - Bengali
    manageUsers: "ব্যবহারকারী ও ভূমিকা পরিচালনা",
    username: "ব্যবহারকারীর নাম",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    roles: "ভূমিকা",
    userActive: "ব্যবহারকারী সক্রিয়",
    addUser: "ব্যবহারকারী যোগ করুন",
    editUser: "ব্যবহারকারী সম্পাদনা করুন",
    deleteUser: "ব্যবহারকারী মুছুন",
    confirmDeleteUser: "আপনি কি সত্যিই এই ব্যবহারকারীকে মুছতে চান?",
    userCreated: "ব্যবহারকারী সফলভাবে তৈরি করা হয়েছে।",
    userUpdated: "ব্যবহারকারী সফলভাবে আপডেট করা হয়েছে।",
    userDeleted: "ব্যবহারকারী সফলভাবে মুছে ফেলা হয়েছে।",
    manageRoles: "ভূমিকা পরিচালনা করুন",
    roleName: "ভূমিকার নাম",
    roleDescription: "বর্ণনা (ঐচ্ছিক)",
    permissions: "অনুমতিসমূহ",
    addRole: "ভূমিকা যোগ করুন",
    editRole: "ভূমিকা সম্পাদনা করুন",
    deleteRole: "ভূমিকা মুছুন",
    confirmDeleteRole: "আপনি কি সত্যিই এই ভূমিকাটি মুছতে চান? এটি সমস্ত ব্যবহারকারীর কাছ থেকে এটিকে সরিয়ে ফেলবে।",
    roleCreated: "ভূমিকা সফলভাবে তৈরি করা হয়েছে।",
    roleUpdated: "ভূমিকা সফলভাবে আপডেট করা হয়েছে।",
    roleDeleted: "ভূমিকা সফলভাবে মুছে ফেলা হয়েছে।",
    cancel: "বাতিল করুন",
    save: "সংরক্ষণ করুন",
    viewAdminDashboardPermission: "অ্যাডমিন ড্যাশবোর্ড দেখুন",
    manageArticlesPermission: "নিবন্ধ পরিচালনা করুন",
    publishArticlesPermission: "নিবন্ধ প্রকাশ করুন",
    manageUsersPermission: "ব্যবহারকারী পরিচালনা করুন",
    manageRolesPermission: "ভূমিকা পরিচালনা করুন",
    manageLayoutGadgetsPermission: "লেআউট/গ্যাজেট পরিচালনা করুন",
    manageSeoGlobalPermission: "গ্লোবাল এসইও পরিচালনা করুন",
    manageSettingsPermission: "সাইট সেটিংস পরিচালনা করুন",
    userAndRoleManagement: "ব্যবহারকারী ও ভূমিকা",
    activityLog: "কার্যকলাপ লগ",
  },
};

export const categories: Category[] = ["Technology", "Sports", "Business", "World", "Entertainment"];

export const initialSampleNewsArticles: NewsArticle[] = [
    {
    id: '1', 
    title: 'Groundbreaking AI Model Released by Tech Giant',
    content: 'A major technology corporation today unveiled a new artificial intelligence model that promises to revolutionize natural language processing. The model, named "Phoenix-7B", boasts an unprecedented number_of_parameters and has demonstrated superior performance in a variety of benchmarks, including text generation, translation, and question answering. Experts believe this could pave the way for more sophisticated AI applications in the near future. The company plans to offer API access to developers starting next quarter.',
    excerpt: 'A new AI model, Phoenix-7B, has been released, promising to revolutionize natural language processing with its advanced capabilities.',
    category: 'Technology',
    publishedDate: '2024-07-28T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/tech1/400/200',
    dataAiHint: 'circuit board',
    authorId: 'env_superadmin', // Example authorId
    metaTitle: 'Tech Giant Unveils Phoenix-7B AI Model',
    metaDescription: 'Explore the groundbreaking Phoenix-7B AI model, set to redefine natural language processing. Learn about its features and future applications.',
    metaKeywords: ['AI', 'Artificial Intelligence', 'Phoenix-7B', 'Tech Giant', 'NLP'],
  },
  {
    id: '2',
    title: 'National Team Secures Victory in World Championship',
    content: 'The national football team clinched a historic victory in the World Championship finals last night after a thrilling match that went into extra time. The winning goal, scored in the 115th minute, sent fans into a frenzy. This marks the team\'s first championship title in over two decades. Celebrations are expected to continue throughout the week across the country. The team captain dedicated the win to their passionate supporters.',
    excerpt: 'The national football team won the World Championship in a thrilling final match, marking their first title in decades.',
    category: 'Sports',
    publishedDate: '2024-07-27T22:30:00Z',
    imageUrl: 'https://picsum.photos/seed/sports1/400/200',
    dataAiHint: 'stadium lights',
    authorId: 'env_superadmin', // Example authorId
  },
];

export const availablePermissions: Permission[] = [
  'view_admin_dashboard',
  'manage_articles',
  'publish_articles',
  'manage_users',
  'manage_roles',
  'manage_layout_gadgets',
  'manage_seo_global',
  'manage_settings',
];
