
import type { NewsArticle, Category } from './types';

export interface LanguageOption {
  value: string;
  label: string;
}

export const languageOptions: LanguageOption[] = [
  { value: 'bn', label: 'Bengali (বাংলা)' },
  { value: 'en', label: 'English' },
  { value: 'hi', label: 'Hindi (हिन्दी)' },
  { value: 'es', label: 'Spanish (Español)' },
  { value: 'fr', label: 'French (Français)' },
  { value: 'ar', label: 'Arabic (العربية)' },
  { value: 'de', label: 'German (Deutsch)' },
  { value: 'ja', label: 'Japanese (日本語)' },
  { value: 'pt', label: 'Portuguese (Português)' },
  { value: 'ru', label: 'Russian (Русский)' },
];

export const defaultLanguage: string = 'bn'; // Default language set to Bengali

export const uiTexts: Record<string, Record<string, string>> = {
  en: {
    appName: "Samay Barta Lite",
    searchPlaceholder: "Search news...",
    allCategories: "All",
    technologyCategory: "Technology",
    sportsCategory: "Sports",
    businessCategory: "Business",
    worldCategory: "World",
    entertainmentCategory: "Entertainment",
    seeMore: "See More",
    backToNews: "Back to News",
    articleNotFound: "Article not found.",
    translationSuccessful: "Translation Successful",
    articleTranslatedTo: "Article translated to",
    translationFailed: "Translation Failed",
    couldNotTranslateArticle: "Could not translate the article. Please try again.",
    displayingOriginal: "Displaying Original",
    showingOriginalContent: "Showing the original article content.",
    translateArticleTitle: "Translate Article", // This was on article page, might not be needed if content auto-translates
    translating: "Translating...",
    translateContent: "Translate Content",
    showOriginal: "Show Original",
    footerReserved: "All rights reserved.",
    footerPoweredBy: "Powered by Next.js & Generative AI",
    theme: "Theme",
    lightTheme: "Light",
    darkTheme: "Dark",
    language: "Language",
    faq: "FAQ",
    termsAndConditions: "Terms & Conditions",
    faqTitle: "Frequently Asked Questions",
    termsTitle: "Terms and Conditions",
    loading: "Loading...",
    noArticlesFound: "No news articles found matching your criteria.",
    articleTitleLabel: "Title",
    articleContentLabel: "Content",
  },
  bn: {
    appName: "সময় বার্তা লাইট",
    searchPlaceholder: "খবর অনুসন্ধান করুন...",
    allCategories: "সব",
    technologyCategory: "প্রযুক্তি",
    sportsCategory: "খেলাধুলা",
    businessCategory: "ব্যবসা",
    worldCategory: "বিশ্ব",
    entertainmentCategory: "বিনোদন",
    seeMore: "আরও দেখুন",
    backToNews: " খবরে ফিরুন",
    articleNotFound: "নিবন্ধটি খুঁজে পাওয়া যায়নি।",
    translationSuccessful: "অনুবাদ সফল হয়েছে",
    articleTranslatedTo: "নিবন্ধটি অনুবাদ করা হয়েছে",
    translationFailed: "অনুবাদ ব্যর্থ হয়েছে",
    couldNotTranslateArticle: "নিবন্ধটি অনুবাদ করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।",
    displayingOriginal: "মূল বিষয়বস্তু প্রদর্শিত হচ্ছে",
    showingOriginalContent: "নিবন্ধটির মূল বিষয়বস্তু দেখানো হচ্ছে।",
    translateArticleTitle: "নিবন্ধ অনুবাদ করুন",
    translating: "অনুবাদ করা হচ্ছে...",
    translateContent: "বিষয়বস্তু অনুবাদ করুন",
    showOriginal: "মূল দেখান",
    footerReserved: "সর্বস্বত্ব সংরক্ষিত।",
    footerPoweredBy: "Next.js এবং জেনারেটিভ AI দ্বারা চালিত",
    theme: "থিম",
    lightTheme: "লাইট",
    darkTheme: "ডার্ক",
    language: "ভাষা",
    faq: "প্রশ্নাবলী",
    termsAndConditions: "শর্তাবলী",
    faqTitle: "সাধারণ জিজ্ঞাস্য প্রশ্নাবলী",
    termsTitle: "শর্তাবলী এবং নিয়মাবলী",
    loading: "লোড হচ্ছে...",
    noArticlesFound: "আপনার মানদণ্ডের সাথে মিলে যাওয়া কোনও সংবাদ নিবন্ধ পাওয়া যায়নি।",
    articleTitleLabel: "শিরোনাম",
    articleContentLabel: "বিষয়বস্তু",
  },
};

export const categories: Category[] = ["Technology", "Sports", "Business", "World", "Entertainment"];

// This can be used for seeding if DB is empty, but primary data source is now MongoDB
export const initialSampleNewsArticles: NewsArticle[] = [
    {
    id: '1', // Will be replaced by MongoDB _id
    title: 'Groundbreaking AI Model Released by Tech Giant',
    content: 'A major technology corporation today unveiled a new artificial intelligence model that promises to revolutionize natural language processing. The model, named "Phoenix-7B", boasts an unprecedented number_of_parameters and has demonstrated superior performance in a variety of benchmarks, including text generation, translation, and question answering. Experts believe this could pave the way for more sophisticated AI applications in the near future. The company plans to offer API access to developers starting next quarter.',
    excerpt: 'A new AI model, Phoenix-7B, has been released, promising to revolutionize natural language processing with its advanced capabilities.',
    category: 'Technology',
    publishedDate: '2024-07-28T10:00:00Z',
    imageUrl: 'https://picsum.photos/seed/tech1/400/200',
    dataAiHint: 'circuit board',
  },
  {
    id: '2',
    title: 'National Team Secures Victory in World Championship',
    content: 'The national football team clinched a historic victory in the World Championship finals last night after a thrilling match that went into extra time. The winning goal, scored in the 115th minute, sent fans into a frenzy. This marks the team\'s first championship title in over two decades. Celebrations are expected to continue throughout the week across the country. The team captain dedicated the win to their passionate supporters.',
    excerpt: 'The national football team won the World Championship in a thrilling final match, marking their first title in decades.',
    category: 'Sports',
    publishedDate: '2024-07-27T22:30:00Z',
    imageUrl: 'https://picsum.photos/seed/sports1/400/200',
    dataAiHint: 'stadium lights',
  },
  {
    id: '3',
    title: 'Stock Market Hits Record High Amidst Positive Economic Indicators',
    content: 'Global stock markets reached new all-time highs this week, fueled by strong corporate earnings reports and positive economic data. Investor confidence appears to be on the rise despite ongoing geopolitical tensions. Analysts suggest that sectors like technology and renewable energy are leading the charge. However, some caution that a market correction could be on the horizon as valuations become stretched.',
    excerpt: 'Global stock markets hit record highs, driven by strong earnings and positive economic news, particularly in tech and renewables.',
    category: 'Business',
    publishedDate: '2024-07-26T15:45:00Z',
    imageUrl: 'https://picsum.photos/seed/business1/400/200',
    dataAiHint: 'city skyline',
  },
  {
    id: '4',
    title: 'International Summit Addresses Climate Change Goals',
    content: 'Leaders from around the world gathered for an international summit focused on tackling climate change. Discussions centered on renewing commitments to reduce carbon emissions and invest in green technologies. While some progress was made, activists argue that the pledges are still insufficient to meet the urgency of the crisis. The summit concluded with a joint declaration outlining future steps and cooperation efforts.',
    excerpt: 'World leaders met at an international summit to discuss climate change, renewing emission reduction commitments.',
    category: 'World',
    publishedDate: '2024-07-25T12:00:00Z',
    imageUrl: 'https://picsum.photos/seed/world1/400/200',
    dataAiHint: 'earth globe',
  },
  {
    id: '5',
    title: 'New Sci-Fi Blockbuster Dominates Summer Box Office',
    content: 'The latest science fiction epic, "Galaxy Wanderers", has taken the summer box office by storm, raking in over $300 million globally in its opening weekend. Directed by acclaimed filmmaker Anya Sharma, the film features stunning visual effects and a compelling storyline that has resonated with audiences and critics alike. It is projected to be one of the highest-grossing films of the year.',
    excerpt: 'Sci-fi blockbuster "Galaxy Wanderers" is dominating the box office with over $300 million in its opening weekend.',
    category: 'Entertainment',
    publishedDate: '2024-07-24T18:00:00Z',
    imageUrl: 'https://picsum.photos/seed/entertainment1/400/200',
    dataAiHint: 'movie theater',
  },
  {
    id: '6',
    title: 'Advancements in Quantum Computing Promise Faster Processing',
    content: 'Researchers have announced a significant breakthrough in quantum computing that could lead to processors capable of speeds unimaginable with current technology. This development focuses on qubit stability and error correction, two major hurdles in the field. While commercial quantum computers are still some years away, this progress accelerates the timeline for their potential impact on science, medicine, and cryptography.',
    excerpt: 'A breakthrough in quantum computing could lead to significantly faster processors, focusing on qubit stability and error correction.',
    category: 'Technology',
    publishedDate: '2024-07-23T09:15:00Z',
    imageUrl: 'https://picsum.photos/seed/tech2/400/200',
    dataAiHint: 'abstract tech',
  },
  {
    id: '7',
    title: 'Local Athlete Smashes National Record in Marathon',
    content: 'Hometown hero Alex Rivera smashed the national marathon record at yesterday\'s city marathon, finishing with an astonishing time of 2 hours and 5 minutes. Rivera, who trained relentlessly for this event, attributed the success to a new training regimen and unwavering community support. The previous record had stood for 15 years.',
    excerpt: 'Local athlete Alex Rivera broke the national marathon record with a time of 2:05, attributing success to new training and support.',
    category: 'Sports',
    publishedDate: '2024-07-22T14:00:00Z',
    imageUrl: 'https://picsum.photos/seed/sports2/400/200',
    dataAiHint: 'running track',
  },
];
