
export interface LanguageOption {
  value: string;
  label: string;
}

export const languageOptions: LanguageOption[] = [
  { value: 'bn', label: 'Bengali (বাংলা)' },
  { value: 'en', label: 'English' },
  { value: 'hi', label: 'Hindi (हिन्दी)' },
  { value: 'es', label: 'Spanish (Español)' },
  { value: 'fr', label: 'French (Français)' },
  { value: 'ar', label: 'Arabic (العربية)' },
  { value: 'de', label: 'German (Deutsch)' },
  { value: 'ja', label: 'Japanese (日本語)' },
  { value: 'pt', label: 'Portuguese (Português)' },
  { value: 'ru', label: 'Russian (Русский)' },
];

export const defaultLanguage: string = 'bn'; // Default language set to Bengali

export const uiTexts: Record<string, Record<string, string>> = {
  en: {
    appName: "Samay Barta Lite",
    searchPlaceholder: "Search news...",
    allCategories: "All",
    technologyCategory: "Technology",
    sportsCategory: "Sports",
    businessCategory: "Business",
    worldCategory: "World",
    entertainmentCategory: "Entertainment",
    seeMore: "See More",
    backToNews: "Back to News",
    articleNotFound: "Article not found.",
    translationSuccessful: "Translation Successful",
    articleTranslatedTo: "Article translated to",
    translationFailed: "Translation Failed",
    couldNotTranslateArticle: "Could not translate the article. Please try again.",
    displayingOriginal: "Displaying Original",
    showingOriginalContent: "Showing the original article content.",
    translateArticleTitle: "Translate Article", // This was on article page, might not be needed if content auto-translates
    translating: "Translating...",
    translateContent: "Translate Content",
    showOriginal: "Show Original",
    footerReserved: "All rights reserved.",
    footerPoweredBy: "Powered by Next.js & Generative AI",
    theme: "Theme",
    lightTheme: "Light",
    darkTheme: "Dark",
    language: "Language",
    faq: "FAQ",
    termsAndConditions: "Terms & Conditions",
    faqTitle: "Frequently Asked Questions",
    termsTitle: "Terms and Conditions",
    loading: "Loading...",
    noArticlesFound: "No news articles found matching your criteria.",
    articleTitleLabel: "Title",
    articleContentLabel: "Content",
  },
  bn: {
    appName: "সময় বার্তা লাইট",
    searchPlaceholder: "খবর অনুসন্ধান করুন...",
    allCategories: "সব",
    technologyCategory: "প্রযুক্তি",
    sportsCategory: "খেলাধুলা",
    businessCategory: "ব্যবসা",
    worldCategory: "বিশ্ব",
    entertainmentCategory: "বিনোদন",
    seeMore: "আরও দেখুন",
    backToNews: " খবরে ফিরুন",
    articleNotFound: "নিবন্ধটি খুঁজে পাওয়া যায়নি।",
    translationSuccessful: "অনুবাদ সফল হয়েছে",
    articleTranslatedTo: "নিবন্ধটি অনুবাদ করা হয়েছে",
    translationFailed: "অনুবাদ ব্যর্থ হয়েছে",
    couldNotTranslateArticle: "নিবন্ধটি অনুবাদ করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।",
    displayingOriginal: "মূল বিষয়বস্তু প্রদর্শিত হচ্ছে",
    showingOriginalContent: "নিবন্ধটির মূল বিষয়বস্তু দেখানো হচ্ছে।",
    translateArticleTitle: "নিবন্ধ অনুবাদ করুন",
    translating: "অনুবাদ করা হচ্ছে...",
    translateContent: "বিষয়বস্তু অনুবাদ করুন",
    showOriginal: "মূল দেখান",
    footerReserved: "সর্বস্বত্ব সংরক্ষিত।",
    footerPoweredBy: "Next.js এবং জেনারেটিভ AI দ্বারা চালিত",
    theme: "থিম",
    lightTheme: "লাইট",
    darkTheme: "ডার্ক",
    language: "ভাষা",
    faq: "প্রশ্নাবলী",
    termsAndConditions: "শর্তাবলী",
    faqTitle: "সাধারণ জিজ্ঞাস্য প্রশ্নাবলী",
    termsTitle: "শর্তাবলী এবং নিয়মাবলী",
    loading: "লোড হচ্ছে...",
    noArticlesFound: "আপনার মানদণ্ডের সাথে মিলে যাওয়া কোনও সংবাদ নিবন্ধ পাওয়া যায়নি।",
    articleTitleLabel: "শিরোনাম",
    articleContentLabel: "বিষয়বস্তু",
  },
};
